#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Slurper
Version  : 0.014
Release  : 24
URL      : https://cpan.metacpan.org/authors/id/L/LE/LEONT/File-Slurper-0.014.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LE/LEONT/File-Slurper-0.014.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-slurper-perl/libfile-slurper-perl_0.012-1.debian.tar.xz
Summary  : 'A simple, sane and efficient module to slurp a file'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-File-Slurper-license = %{version}-%{release}
Requires: perl-File-Slurper-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Warnings)

%description
This archive contains the distribution File-Slurper,
version 0.014:
A simple, sane and efficient module to slurp a file

%package dev
Summary: dev components for the perl-File-Slurper package.
Group: Development
Provides: perl-File-Slurper-devel = %{version}-%{release}
Requires: perl-File-Slurper = %{version}-%{release}

%description dev
dev components for the perl-File-Slurper package.


%package license
Summary: license components for the perl-File-Slurper package.
Group: Default

%description license
license components for the perl-File-Slurper package.


%package perl
Summary: perl components for the perl-File-Slurper package.
Group: Default
Requires: perl-File-Slurper = %{version}-%{release}

%description perl
perl components for the perl-File-Slurper package.


%prep
%setup -q -n File-Slurper-0.014
cd %{_builddir}
tar xf %{_sourcedir}/libfile-slurper-perl_0.012-1.debian.tar.xz
cd %{_builddir}/File-Slurper-0.014
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/File-Slurper-0.014/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-File-Slurper
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-File-Slurper/65782eb205fe12434dd09f9b3c230816d7210a05 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/File::Slurper.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-File-Slurper/65782eb205fe12434dd09f9b3c230816d7210a05

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
